# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7ea4cb6e2833f29b2f14bcc36ea06d46f45e273a80ad77276a0d7b95070f2c69fa5e92d92f9c51199196b4993103ff542af3ab4a656e32f9d46d25f8bd3c23

test:
  secret_key_base: b26719c9f512fa1a59e85a9bf67e3bae4ef4ebd1990a7d854eeaeb59f20dff4d666f8f87c35c4b3d895a519c6ffaf20ec23906890c063fe1212afc547b1d09b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
